# Generated by Django 3.2.7 on 2021-09-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_platform_instance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemption',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
